### ISSUE TITLE
support installing pre-compiled fontc using cargo-binstall

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontc-action#17]
now that fontc will be publishing precompiled binary artifacts in its Github Releases that are suitable for `cargo binstall` command (https://github.com/googlefonts/fontc/pull/827), I think this fontc-action could be modified to use that when available, or maybe install `cargo binstall` and attempt to install the latest, precompiled `fontc` unless the user passes options to select specific commits or branches etc. which would force building from source with regular `cargo install` command.

Or maybe check if fontc is already present (cargo binstall-ed beforehand) and skip compiling fontc from source. But then.. this whole action becomes a bit useless and one could simply do:

```yml
name: Install fontc and Compile Fonts

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build fonts
    steps:
      - name: Check out font project source repository
        uses: actions/checkout@v4
      - name: Install the latest stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install the latest fontc
        run: cargo binstall fontc
      # - name: Install a specific fontc version
      #   run: cargo binstall fontc@0.0.1
      - name: Compile font
        run: fontc source/Font.glyphs
```
