### ISSUE TITLE
Fetch the binary and don't require a rust toolchain

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontc-action#18]
Use published binary of compiler. That should mean we don't need a rust toolchain.

**Comment by chrissimpkins** [comment]
@rsheeter @cmyr @anthrotype Can we begin releasing fontc regularly to support this?

**Comment by anthrotype** [comment]
> Can we begin releasing fontc regularly to support this?

Rod pushed this yesterday: https://github.com/googlefonts/fontc/releases/tag/fontc-v0.1.0

If you have [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) you can do `cargo binstall fontc` (to install the latest) or `cargo binstall fontc@0.1.0` to install a specific pinned version, and it will download it from Github and install the right precompiled fontc binary in a couple of seconds.

Alternatively if you have python and prefer to use pip, you can also do `pip install fontc` or `pip install --upgrade fontc` or `pip install fontc==0.1.0` etc. as usual.

**Comment by anthrotype** [comment]
e.g. this should already work

```yaml
steps:
  - name: Install cargo-binstall
    uses: cargo-bins/cargo-binstall@v1

  - name: Use cargo-binstall to grab precompiled fontc
    run: cargo binstall fontc@0.1.0
```

**Comment by chrissimpkins** [comment]
Thanks!  It sounds like we no longer need this Action?

**Comment by anthrotype** [comment]
well, it'd still be nice for people who are not software developers but are just interested in building the fonts themselves to be able to do just that in one go 

```yaml
      - name: Install fontc and compile fonts
        uses: googlefonts/fontc-action@main
        with:
          source-path: src/TestFont.glyphs
```
